version: '3.8'

services:
  # PostgreSQL with PostGIS
  postgres:
    image: postgis/postgis:15-3.3
    container_name: rnep_postgres
    environment:
      POSTGRES_DB: rnep_db
      POSTGRES_USER: rnep_user
      POSTGRES_PASSWORD: rnep_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rnep_user -d rnep_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: rnep_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RNEP API (for development)
  # Uncomment when Dockerfile is ready
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: rnep_api
  #   environment:
  #     DATABASE_URL: postgresql+asyncpg://rnep_user:rnep_password@postgres:5432/rnep_db
  #     REDIS_URL: redis://redis:6379/0
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./rnep:/app/rnep
  #     - ./data:/app/data
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   command: uvicorn rnep.api.main:app --host 0.0.0.0 --port 8000 --reload

  # pgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: rnep_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@rnep.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # Redis Commander for Redis management (optional)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: rnep_redis_commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  default:
    name: rnep_network